spring.application.name=online-voting

# ===============================
# DATABASE CONFIGURATION (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/online_voting_system?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
# Ye setting console me SQL queries print karegi (Debugging ke liye badhiya hai)
spring.jpa.show-sql=true
# Ye 'update' rakha hai taaki agar hum Java class me kuch change karein, toh table apne aap update ho jaye
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# EMAIL CONFIGURATION (OTP Ke liye)
# ===============================
# Abhi ke liye hum Gmail ka SMTP server use kar sakte hain
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Apna woh email daalein jisse aap OTP bhejna chahte hain
spring.mail.username=worthlesssharma@gmail.com
# Yahan apna normal password nahi daalna hai! Gmail se 'App Password' generate karke daalna hoga.
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
